# fly.toml app configuration file generated for fluxzero-cli-api on 2025-09-26T15:50:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fluxzero-cli-api'
primary_region = 'ams'

[build]

[env]
  TZ = 'UTC'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
