### Generate project
#POST http://localhost:8080/api/init
POST https://fluxzero-cli-api-production.rene7346.workers.dev/api/init
Content-Type: application/json

{
    "template": "flux-basic-kotlin",
    "name": "some-name",
    "packageName": "some.package",
    "groupId": "com.somegroup",
    "buildSystem": "maven"
}

###